# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0048_auto_20191024_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dictionary.FieldChoice', to_field='machine_value', verbose_name='Location'),
        ),
    ]
